apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kiali-podmonitor
  namespace: istio-system
  labels:
    monitoring: kiali
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kiali
  namespaceSelector:
    matchNames:
      - istio-system
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kiali-servicemonitor
  namespace: istio-system
  labels:
    monitoring: kiali
    release: kube-prometheus-stack
spec:
  jobLabel: app.kubernetes.io/name
  targetLabels:
    - app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: kiali
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
