apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Application
      name: kiali-operator
    patch: |-
      - op: replace
        path: /spec/source/helm/values
        value: |
          cr:
            create: true
            namespace: istio-system
            spec:
              auth:
                strategy: anonymous
