apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/cert-manager-crds.yaml  
  - base/grafana-app.yaml
  - base/kiali-app.yaml
  - base/jaeger-app.yaml
  - base/prometheus-app.yaml