apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: coder
    repo: https://helm.coder.com
    version: 2.7.2
    releaseName: coder
    namespace: coder
    valuesFile: values.yaml
