# apps/kafka/base/values.yaml
kafka:
  kraft:
    enabled: true
    controller:
      replicaCount: 1
    broker:
      replicaCount: 2

  zookeeper:
    enabled: false

metrics:
  jmx:
    enabled: true
    config: |-
      lowercaseOutputName=true
      whitelistObjectNames=["kafka.server:*"]
      rules=[
        {
          pattern: "kafka.server<type=(.+), name=(.+)><>(Count|Value)",
          name: "kafka_server_$1_$2",
          type: "GAUGE"
        }
      ]

  serviceMonitor:
    enabled: true
    interval: 10s
    scrapeTimeout: 10s
    labels:
      release: prometheus
