apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 19.0.1
    releaseName: redis
    namespace: cache
    valuesFile: values.yaml
