apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 13.2.24
    releaseName: coder-postgresql
    namespace: coder
    valuesFile: values.yaml
