# Your customized values to enable metrics, servicemonitors, alerting, etc.
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        release: kube-prometheus-stack
    podMonitorSelector:
      matchLabels:
        release: kube-prometheus-stack
alertmanager:
  alertmanagerSpec:
    serviceMonitorSelector:
      matchLabels:
        release: kube-prometheus-stack
