prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

kube-prometheus-stack:
  grafana:
    sidecar:
      dashboards:
        enabled: true
      datasources:
        enabled: true
