apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana-operator
    targetRevision: v5.18.0
    helm:
      values: |
        adminUser: admin
        adminPassword: prom-operator
        service:
          type: ClusterIP
        persistence:
          enabled: true
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          size: 1Gi
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local
                access: proxy
                isDefault: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
