apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-monitor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cyberforge33/argocd-app-config.git
    targetRevision: HEAD
    path: apps/istio/istio-monitor
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-monitor
  syncPolicy:
    syncOptions:
      - CreateNamespace=true      
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
