apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger-operator
    targetRevision: 2.57.0  # Use the latest stable version
    helm:
      values: |
        strategy: production
        collector:
          enabled: true
        query:
          enabled: true
        agent:
          enabled: true
        storage:
          type: elasticsearch
          options:
            es:
              server-urls: http://elasticsearch-master:9200
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
