apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-operator
    targetRevision: 2.10.0
    helm:
      values: |        
        cr:
          create: true
          namespace: istio-system
          spec:
            auth:
              strategy: anonymous
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true      
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true