apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-monitors
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cyberforge33/argocd-app-config.git
    targetRevision: HEAD
    path: apps/service-monitors
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true      
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
