apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kiali-servicemonitor
  namespace: istio-system
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: kiali
  targetLabels: [app]
  selector:
    matchLabels:
      app: kiali
  namespaceSelector:
    any: true
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s